### ISSUE TITLE
Error plotting Wiki example 1

### ISSUE THREAD

**Issue by gvegayon** [gvegayon/rgexf#29]
Originally reported by: **Brian Davis (Bitbucket: [brian_davis_](https://bitbucket.org/brian_davis_), GitHub: Unknown)**

----------------------------------------

I'm new to this so it's probably user error but when I try to plot Example 1 in the Wiki I get an error and I'm not sure how to proceed.

> library(rgexf)

> people <- data.frame(matrix(c(1:4, 'juan', 'pedro', 'matthew', 'carlos'),ncol=2))

> relations <- data.frame(matrix(c(1,4,1,2,1,3,2,3,3,4,4,2), ncol=2, byrow=T))

> g <- write.gexf(people, relations)

> plot(g, EdgeType="curve")

Error in paste("http://", listenAddr, ":", listenPort, appList[[i]]$path,  : 
  cannot coerce type 'closure' to vector of type 'character'

Am 

----------------------------------------
- Bitbucket: https://bitbucket.org/gvegayon/rgexf/issue/29

**Comment by gvegayon** [comment]
@jbkunst working on it =)

**Comment by gvegayon** [comment]
Ping to @jbkunst :smile:

**Comment by jbkunst** [comment]
Ok ok! Sorry! :disappointed: I will look the issue this week :wink:
