### ISSUE TITLE
Attributes not included when reading in .gexf file

### ISSUE THREAD

**Issue by HolzmanoLagrene** [gvegayon/rgexf#35]
When reading in a gexf-file created by networkx, even though all attributes are contained in the xml-code, they are not accessible when running `read.gexf` and disappear completely when transform into igraph object.

**Comment by gvegayon** [comment]
Please provide with a reproducible example (hopefully some data) so I can see the problem directly. Thanks

**Comment by jintrone** [comment]
Encountered the same problem, attempting to read a file exported by gephi with modularity class defined on vertices.  Attaching the graph file here:  [know_network_markup3.gexf.zip](https://github.com/gvegayon/rgexf/files/3824657/know_network_markup3.gexf.zip). After reading in with `read.gexf` i see the attribute defined:

```r
> g<-read.gexf(file)
> g[["atts.definitions"]]
$nodes
                id            title    type
1 modularity_class Modularity Class integer

$edges
NULL
```

But there is no attribute information associated with the nodes.

```r
> head(g[["nodes"]])
   id label
1   0     0
2   4     4
3  68    68
4 512   512
5 516   516
6 580   580
```

Converting to iGraph drops the attribute entirely:

```r
> i<-gexf.to.igraph(g)
> list.vertex.attributes(i)
[1] "name"
```

Thanks for any help!

**Comment by gvegayon** [comment]
Solved
