### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by sciatro** [gvegayon/rgexf#37]
Looks like this package was removed from CRAN

    Package ‘rgexf’ was removed from the CRAN repository.

    Formerly available versions can be obtained from the archive.

    Archived on 2020-01-16 as check issues were not corrected in time. 

- https://cran.r-project.org/web/packages/rgexf/index.html

**Comment by gvegayon** [comment]
Yes, I saw that :P.I'm working on an update. Should be there soon. Thanks

**Comment by sciatro** [comment]
Excellent. Thank you for this most useful package.

**Comment by gvegayon** [comment]
On CRAN now
