### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by Arf9999** [gvegayon/rgexf#39]
I'm trying to build gexf graph files from {rtweet} dataframes.  I've created node and edge data.frames that should satisfy requirements for write.gexf, but get the following parsing error:

`Error: 1: error parsing attribute name
2: attributes construct error
3: Couldn't find end of Start Tag node line 1
4: Opening and ending tag mismatch: tmp line 1 and node
5: Extra content at the end of the document `

I really don't know what the issue is (XML isn't one of my skills).  I've tried to sanitize the XML for nodes as well as source and target in the edges df, but to no avail.

**Comment by gvegayon** [comment]
Could you provide a sample of the data you are trying to use with rgexf?

**Comment by Arf9999** [comment]
I think I've fixed it.  I was passing two columns of a larger dataframe as nodes into write.gexf`, I've no wcreated a separate dataframe of those columns first.  Seems to have fixed the issue.  

Thanks for the response

**Comment by gvegayon** [comment]
Cannot reproduce this error.
