### ISSUE TITLE
Reading in graph with hexadecimal colours

### ISSUE THREAD

**Issue by milnus** [gvegayon/rgexf#41]
Hi George,
I'm trying to read in a graph with node colours specified as hexadecimals (attach is a subset of three nodes and two edges from the graph that produce the error in question).
When I try to load in the graph I get the following error:

`Error in if (x < 1) stop("When specified as number, colors cannot be negative!",  :` 
`  missing value where TRUE/FALSE needed`
`In addition: Warning message:`
`In check_and_map_color(as.numeric(a$color)) : NAs introduced by coercion` 

I have narrowed it down to the hexadecimal sting being converted to NA by the `as.numeric()` when calling `check_and_map_color` in line 58 of 'read.gexf()'. The NA is accepted as a numeric in line 4 of 'check_and_map_color', and then conflicts with the if-statement of line 5.

Is there a reason for the 'as.numeric()' function call on the colour in line 58 of 'read.gexf()' when calling 'check_and_map_color'?
I can see that 'check_and_map_color' is able to handle hexadecimal colours, as I tried to remove the 'as.numeric()' call and was able to read in the test graph provided. I hope you can clarify

[Hex_col_test.txt](https://github.com/gvegayon/rgexf/files/5315284/Hex_col_test.txt)

Cheers,
Magnus

**Comment by gvegayon** [comment]
Solved in #43
