### ISSUE TITLE
Error in x[2, 4] : incorrect number of dimensions

### ISSUE THREAD

**Issue by IsabelFE** [gvegayon/rgexf#42]
Hello,

I am trying to use read.gexf() to read a .gexf generated with the pangenomic package PPanGGOLiN (https://github.com/labgem/PPanGGOLiN) and it gets the following error:

```
> gephy <- read.gexf("pangenomeGraph.gexf")
Unsupported version '1.1'
Error in x[2, 4] : incorrect number of dimensions
In addition: Warning message:
In if ((x[-4] < 0) | (x[-4] > 255)) stop("The color specification is out of range.",  :
  the condition has length > 1 and only the first element will be used
```

Thanks for any suggestions!

Isabel

**Comment by gvegayon** [comment]
Thanks for reporting this, I believe the bug has been solved with https://github.com/gvegayon/rgexf/commit/92778d0471a83e37269ecb96f394cb06b91be6f7. Feel free to reopen the issue if the problem is still there.
